[package]
name = "idlemapper"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Wire up various idle apis"

[dependencies]
futures = "0.3"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
zbus = "2.0.0-beta.3"
